### ISSUE TITLE
Docker - There are no configured topics. The application will now exit

### ISSUE THREAD

**Issue by Ryan-RJM** [pmcilreavy/AzureEventGridSimulator#138]
When running the Azure Event Grid Simulator on docker, with the ConfigFile environment variable defined, it exits with this error:
"There are no configured topics. The application will now exit"

### docker-compose.yml
```
version: "3.9"
services:
  eventgrid:
    image: pmcilreavy/azureeventgridsimulator:latest
    restart: unless-stopped
    ports:
      - 60101:60101
    volumes:
      - S:\Development\AzureEventGridSimulator\docker:/aegs:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/aegs/azureEventGridSimulator.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - TZ=Europe/London
      - AEGS_Serilog__MinimumLevel__Default=Verbose
      - ConfigFile=/aegs/config.json
```

### config.json
```
{
  "topics": [
    {
      "name": "MyAwesomeTopic",
      "port": 60101,
      "key": "TheLocal+DevelopmentKey=",
      "subscribers": [
        {
          "name": "LocalAzureFunctionSubscription",
          "endpoint": "http://localhost:7071/runtime/webhooks/EventGrid?functionName=PersistEventToDb",
          "filter": {
            "includedEventTypes": ["my.eventType"]
          }
        }
      ]
    }
  ]
}
```

### Directory Files
![image](https://user-images.githubusercontent.com/47944866/212176749-67a1fd91-06ef-4b7d-a760-e25a31917e2b.png)

### Error
![image](https://user-images.githubusercontent.com/47944866/212177026-6f9e510f-de2c-4a4a-9939-2b2aafce54c0.png)
